GROQ_API_KEY = ""
DB_CONN_STR = ""
DB_USERNAME = ""
DB_PASSWORD = ""
DB_BUCKET = "pdf-docs"
DB_SCOPE = "shared"
DB_COLLECTION = "docs"
INDEX_NAME = "pdf_search"
LOGIN_PASSWORD = ""
GOOGLE_API_KEY = ""
OPENAI_API_KEY = ""
OLLAMA_URL="http://localhost:11434"

